# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [1]:
import numpy as np

## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [2]:
grades = np.array([77, 85, 56, 90, 66])
avg = grades.mean()
summation = grades.sum()
print("average = {}, sum = {}".format(avg,summation))

average = 74.8, sum = 374


最大值

In [3]:
grades.max()

90

標準差

In [4]:
grades.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [6]:
prices = np.array([1096.95, 596.95, 896.95])
prices*31.71

array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [7]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])

### 【技巧】 一行完成成績計算

In [8]:
grades.dot(weights)

77.5

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [9]:
A = np.random.random(50)
A

array([0.47880707, 0.47478157, 0.42068165, 0.97280241, 0.28281422,
       0.04722945, 0.84008428, 0.62455406, 0.5303179 , 0.14260457,
       0.90177181, 0.75464479, 0.2182432 , 0.06093473, 0.93076729,
       0.95439512, 0.68976112, 0.45973936, 0.03746823, 0.82330273,
       0.19271121, 0.8912336 , 0.72255624, 0.72142239, 0.59831446,
       0.9434529 , 0.76931593, 0.16974962, 0.84866327, 0.76731793,
       0.08772286, 0.68315875, 0.95511064, 0.58497669, 0.33720942,
       0.89584316, 0.6534247 , 0.91006799, 0.2971528 , 0.4685291 ,
       0.56585972, 0.29070124, 0.35220022, 0.43108898, 0.8902594 ,
       0.71358799, 0.45372162, 0.45569909, 0.19719486, 0.13334814])

### 【技巧】 檢查 A 的 `shape`

In [10]:
A.shape

(50,)

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [11]:
A.reshape(-1,5)

array([[0.47880707, 0.47478157, 0.42068165, 0.97280241, 0.28281422],
       [0.04722945, 0.84008428, 0.62455406, 0.5303179 , 0.14260457],
       [0.90177181, 0.75464479, 0.2182432 , 0.06093473, 0.93076729],
       [0.95439512, 0.68976112, 0.45973936, 0.03746823, 0.82330273],
       [0.19271121, 0.8912336 , 0.72255624, 0.72142239, 0.59831446],
       [0.9434529 , 0.76931593, 0.16974962, 0.84866327, 0.76731793],
       [0.08772286, 0.68315875, 0.95511064, 0.58497669, 0.33720942],
       [0.89584316, 0.6534247 , 0.91006799, 0.2971528 , 0.4685291 ],
       [0.56585972, 0.29070124, 0.35220022, 0.43108898, 0.8902594 ],
       [0.71358799, 0.45372162, 0.45569909, 0.19719486, 0.13334814]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [12]:
A.ravel()

array([0.47880707, 0.47478157, 0.42068165, 0.97280241, 0.28281422,
       0.04722945, 0.84008428, 0.62455406, 0.5303179 , 0.14260457,
       0.90177181, 0.75464479, 0.2182432 , 0.06093473, 0.93076729,
       0.95439512, 0.68976112, 0.45973936, 0.03746823, 0.82330273,
       0.19271121, 0.8912336 , 0.72255624, 0.72142239, 0.59831446,
       0.9434529 , 0.76931593, 0.16974962, 0.84866327, 0.76731793,
       0.08772286, 0.68315875, 0.95511064, 0.58497669, 0.33720942,
       0.89584316, 0.6534247 , 0.91006799, 0.2971528 , 0.4685291 ,
       0.56585972, 0.29070124, 0.35220022, 0.43108898, 0.8902594 ,
       0.71358799, 0.45372162, 0.45569909, 0.19719486, 0.13334814])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### 【技巧】單位矩陣

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [16]:
np.linspace(0,10,25) #切分成多少數量

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

### 【技巧】`range` 的 array 版

就是 `arange`。

In [17]:
np.arange(0,10,2) #間隔的概念

array([0, 2, 4, 6, 8])

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [18]:
B = np.arange(10).reshape(2,-1)
B

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [19]:
B.sum(axis=0)

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [20]:
B.sum(axis=1)

array([10, 35])

### 【提示】當然也有可能全部算

In [21]:
B.sum()

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [22]:
L = np.array([3, -2, -1, 5, 7, -3])

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!

In [25]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [26]:
L[L>0]

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [27]:
C = np.arange(10)
C

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
C[3:7]

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [29]:
C = C.reshape(2,-1)
C

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [30]:
C[:,1:3]

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [31]:
C[1,:]

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [32]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [33]:
D = np.c_[x,y]
D

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [34]:
E = np.r_[x,y]
E

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [35]:
D[:,0]

array([1, 2, 3, 4])